### ISSUE TITLE
carousel-indicators not working on clicking

### ISSUE THREAD

**Issue by rajdeepbharati** [neilchauhan2/Community-Website#2]
Hi there!
The carousel indicators are not working when we are clicking on them. Do you want me to work on this issue?

**Comment by candy-j** [comment]
Thank you,  Mr. Rajdeep bharati for your enthusiastic investigation on the project. 
However, we want to bring to your notice that, we have manually checked the issue and we didn't find any problems,  everything is working just perfect.

What you might want to do: 
Step 1 git pull
Step 2 clear cache 
Step 3 python manage.py collectstatic 

If it still didn't rectify your problem, please let us know through mail. 

We will try our best to help you out.

**Comment by neilchauhan2** [comment]
@rajdeepbharati please go ahead and solve the issue, I'll review the pull request and merge it, if everything seems fine.

**Comment by rajdeepbharati** [comment]
@neilchauhan2 I've fixed it, you can review it now.

**Comment by pengoox** [comment]
It fixed the looping problem.
