### ISSUE TITLE
Carousel bug

### ISSUE THREAD

**Issue by neilchauhan2** [neilchauhan2/Community-Website#5]
The Carousel indicators are not working.

**Comment by LS05** [comment]
Hey, @neilchauhan2 what's exactly the issue?

**Comment by neilchauhan2** [comment]
@LS05 05 on the website [https://opendevx2.pythonanywhere.com](https://opendevx2.pythonanywhere.com) you'll find in the carousel (i.e. slideshow) the indicators at the bottom are not working. They are not being highlighted as the slide changes. Moreover, on clicking the last two indicators the the slide doesn't change.
